# Generated by Django 4.2.16 on 2024-10-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
